/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuyerListRouteImport } from './routes/buyer-list'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as EmailRouteImport } from './routes/email'
import { Route as HomeRouteImport } from './routes/home'
import { Route as KpiTrackerRouteImport } from './routes/kpi-tracker'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as RehabCalcRouteImport } from './routes/rehab-calc'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SmsRouteImport } from './routes/sms'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as TitleCompaniesRouteImport } from './routes/title-companies'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyerListRoute = BuyerListRouteImport.update({
  id: '/buyer-list',
  path: '/buyer-list',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailRoute = EmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const KpiTrackerRoute = KpiTrackerRouteImport.update({
  id: '/kpi-tracker',
  path: '/kpi-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const RehabCalcRoute = RehabCalcRouteImport.update({
  id: '/rehab-calc',
  path: '/rehab-calc',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsRoute = SmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleCompaniesRoute = TitleCompaniesRouteImport.update({
  id: '/title-companies',
  path: '/title-companies',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buyer-list': typeof BuyerListRoute
  '/calendar': typeof CalendarRoute
  '/calls': typeof CallsRoute
  '/communications': typeof CommunicationsRoute
  '/contacts': typeof ContactsRoute
  '/email': typeof EmailRoute
  '/home': typeof HomeRoute
  '/kpi-tracker': typeof KpiTrackerRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRoute
  '/properties': typeof PropertiesRoute
  '/rehab-calc': typeof RehabCalcRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/tasks': typeof TasksRoute
  '/title-companies': typeof TitleCompaniesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buyer-list': typeof BuyerListRoute
  '/calendar': typeof CalendarRoute
  '/calls': typeof CallsRoute
  '/communications': typeof CommunicationsRoute
  '/contacts': typeof ContactsRoute
  '/email': typeof EmailRoute
  '/home': typeof HomeRoute
  '/kpi-tracker': typeof KpiTrackerRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRoute
  '/properties': typeof PropertiesRoute
  '/rehab-calc': typeof RehabCalcRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/tasks': typeof TasksRoute
  '/title-companies': typeof TitleCompaniesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buyer-list': typeof BuyerListRoute
  '/calendar': typeof CalendarRoute
  '/calls': typeof CallsRoute
  '/communications': typeof CommunicationsRoute
  '/contacts': typeof ContactsRoute
  '/email': typeof EmailRoute
  '/home': typeof HomeRoute
  '/kpi-tracker': typeof KpiTrackerRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/payments': typeof PaymentsRoute
  '/pipeline': typeof PipelineRoute
  '/properties': typeof PropertiesRoute
  '/rehab-calc': typeof RehabCalcRoute
  '/settings': typeof SettingsRoute
  '/sms': typeof SmsRoute
  '/tasks': typeof TasksRoute
  '/title-companies': typeof TitleCompaniesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buyer-list'
    | '/calendar'
    | '/calls'
    | '/communications'
    | '/contacts'
    | '/email'
    | '/home'
    | '/kpi-tracker'
    | '/leads'
    | '/login'
    | '/payments'
    | '/pipeline'
    | '/properties'
    | '/rehab-calc'
    | '/settings'
    | '/sms'
    | '/tasks'
    | '/title-companies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buyer-list'
    | '/calendar'
    | '/calls'
    | '/communications'
    | '/contacts'
    | '/email'
    | '/home'
    | '/kpi-tracker'
    | '/leads'
    | '/login'
    | '/payments'
    | '/pipeline'
    | '/properties'
    | '/rehab-calc'
    | '/settings'
    | '/sms'
    | '/tasks'
    | '/title-companies'
  id:
    | '__root__'
    | '/'
    | '/buyer-list'
    | '/calendar'
    | '/calls'
    | '/communications'
    | '/contacts'
    | '/email'
    | '/home'
    | '/kpi-tracker'
    | '/leads'
    | '/login'
    | '/payments'
    | '/pipeline'
    | '/properties'
    | '/rehab-calc'
    | '/settings'
    | '/sms'
    | '/tasks'
    | '/title-companies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyerListRoute: typeof BuyerListRoute
  CalendarRoute: typeof CalendarRoute
  CallsRoute: typeof CallsRoute
  CommunicationsRoute: typeof CommunicationsRoute
  ContactsRoute: typeof ContactsRoute
  EmailRoute: typeof EmailRoute
  HomeRoute: typeof HomeRoute
  KpiTrackerRoute: typeof KpiTrackerRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  PaymentsRoute: typeof PaymentsRoute
  PipelineRoute: typeof PipelineRoute
  PropertiesRoute: typeof PropertiesRoute
  RehabCalcRoute: typeof RehabCalcRoute
  SettingsRoute: typeof SettingsRoute
  SmsRoute: typeof SmsRoute
  TasksRoute: typeof TasksRoute
  TitleCompaniesRoute: typeof TitleCompaniesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buyer-list': {
      id: '/buyer-list'
      path: '/buyer-list'
      fullPath: '/buyer-list'
      preLoaderRoute: typeof BuyerListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email': {
      id: '/email'
      path: '/email'
      fullPath: '/email'
      preLoaderRoute: typeof EmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kpi-tracker': {
      id: '/kpi-tracker'
      path: '/kpi-tracker'
      fullPath: '/kpi-tracker'
      preLoaderRoute: typeof KpiTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rehab-calc': {
      id: '/rehab-calc'
      path: '/rehab-calc'
      fullPath: '/rehab-calc'
      preLoaderRoute: typeof RehabCalcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms': {
      id: '/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof SmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title-companies': {
      id: '/title-companies'
      path: '/title-companies'
      fullPath: '/title-companies'
      preLoaderRoute: typeof TitleCompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyerListRoute: BuyerListRoute,
  CalendarRoute: CalendarRoute,
  CallsRoute: CallsRoute,
  CommunicationsRoute: CommunicationsRoute,
  ContactsRoute: ContactsRoute,
  EmailRoute: EmailRoute,
  HomeRoute: HomeRoute,
  KpiTrackerRoute: KpiTrackerRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  PaymentsRoute: PaymentsRoute,
  PipelineRoute: PipelineRoute,
  PropertiesRoute: PropertiesRoute,
  RehabCalcRoute: RehabCalcRoute,
  SettingsRoute: SettingsRoute,
  SmsRoute: SmsRoute,
  TasksRoute: TasksRoute,
  TitleCompaniesRoute: TitleCompaniesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
