/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as CommunicationsRouteImport } from './routes/communications'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as PipelineRouteImport } from './routes/pipeline'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunicationsRoute = CommunicationsRouteImport.update({
  id: '/communications',
  path: '/communications',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/communications': typeof CommunicationsRoute
  '/leads': typeof LeadsRoute
  '/pipeline': typeof PipelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/communications': typeof CommunicationsRoute
  '/leads': typeof LeadsRoute
  '/pipeline': typeof PipelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calls': typeof CallsRoute
  '/communications': typeof CommunicationsRoute
  '/leads': typeof LeadsRoute
  '/pipeline': typeof PipelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/calls' | '/communications' | '/leads' | '/pipeline'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calls' | '/communications' | '/leads' | '/pipeline'
  id: '__root__' | '/' | '/calls' | '/communications' | '/leads' | '/pipeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CallsRoute: typeof CallsRoute
  CommunicationsRoute: typeof CommunicationsRoute
  LeadsRoute: typeof LeadsRoute
  PipelineRoute: typeof PipelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communications': {
      id: '/communications'
      path: '/communications'
      fullPath: '/communications'
      preLoaderRoute: typeof CommunicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CallsRoute: CallsRoute,
  CommunicationsRoute: CommunicationsRoute,
  LeadsRoute: LeadsRoute,
  PipelineRoute: PipelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
